site_name: My linux notes
site_url: https://vladimirsbelajevs.github.io/linux-docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: cyan
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
